### ISSUE TITLE
M-switch acuation

### ISSUE THREAD

**Issue by jsakkos-curio** [Fluigent/fgt-SDK#56] opened 2022-12-06 16:38 UTC
We've had some issues with the M-switches actuating consistently. Sometimes, we get a non-zero error code and can wake the device(s) from sleep, but this sometimes requires a full reboot of the controller, not simply to set the power to 1. Additionally, devices often report correct actuation (error code 0), but fail to actuate. We catch these by the actuation time, which, in our testing, should not be less than 0.3s and non-zero. Here is a sample script that reproduces the issue:

```from Fluigent.SDK import fgt_init, fgt_close
from Fluigent.SDK import fgt_SWITCH_DIRECTION
from Fluigent.SDK import fgt_get_valveChannelCount
from Fluigent.SDK import (
    fgt_get_valveRange,
    fgt_get_valvePosition,
    fgt_set_valvePosition,
    fgt_set_power,
    fgt_get_valveChannelCount,
    fgt_set_sensorRegulation,
    fgt_get_sensorValue,
    fgt_get_sensorRange,
    fgt_set_pressure,
    fgt_get_pressure,
)

from tqdm import tqdm
import random
import time


def run():
    """Test M-switch fault by actuating to random positions."""
    fgt_init()
    m_switch_list = list()

    faults = dict()
    # Only test M-switches
    for valve in range(fgt_get_valveChannelCount(0)):
        if fgt_get_valveRange(valve) > 1:
            m_switch_list.append(valve)
            faults.update({valve: 0})
    # Loop 1000 over each switch by randomly selecting a switch (if there are multiple) and randomly setting a position.
    for _ in tqdm(range(1000 * len(m_switch_list))):
        switch = random.choice(m_switch_list)
        position = random.randint(0, 9)
        t1 = time.time()
        error_code = fgt_set_valvePosition(
            switch, position, direction=fgt_SWITCH_DIRECTION.Shortest, wait=1
        )
        t2 = time.time()
        # time.sleep(2.5)
        ret_val = verify_switch_actuation(switch, position, error_code, t1, t2)
        faults.update({switch: faults[switch] + ret_val})

    fgt_close()
    return faults


def verify_switch_actuation(
    switch: int, position: int, error_code, t1, t2, actuation_time=0.3
):
    """Check that M-switches actuate as expected via error code and the switching duration. For durations less than 0.5 seconds but not 0, the switch has likely failed to actuate and requires waking from sleep.

    Args:
        switch (int): Switch selection, 0 or 1.
        position (int): Switch position, 0 to 9.
        error_code (_type_): Error code returned by the switch after actuation. See Fluigent SDK for list of error codes.
        t1 (float): Start time
        t2 (float): End time
    """
    # Check error code and actuation time
    if error_code.__dict__["_fgt_ENUM__value"] != 0 or (
        (t2 - t1) > 0 and (t2 - t1) < actuation_time
    ):
        print(error_code)
        print(
            f"Failed to actuate at position ({switch},{position}) with an actuation time of {t2-t1} seconds. Rebooting controller."
        )
        ############# Comment this section out to verify that the switch does not phyiscally actuate when this if statement is true.
        # Turn off LineUP Controller
        error_code = fgt_set_power(0, 0)
        time.sleep(5)
        # Turn on LineUP Controller
        error_code = fgt_set_power(0, 1)
        time.sleep(5)
        fgt_close()
        #############
        # If the switch fails to actuate, try 5 more times to verify.
        for i in range(5):
            new_position = random.randint(0, 9)
            t1 = time.time()
            error_code = fgt_set_valvePosition(
                switch, position, direction=fgt_SWITCH_DIRECTION.Shortest, wait=1
            )
            t2 = time.time()
            time.sleep(2.5)
            # Reset 2-switch to open
            print(
                f"Actuated at position ({switch},{new_position}) with an actuation time of {t2-t1} seconds."
            )

        return 1
        # if error_code.__dict__["_fgt_ENUM__value"] != 0 or (
        #     (t2 - t1) > 0 and (t2 - t1) < actuation_time
        # ):
        #     print(error_code)
        #     print("Unable to wake M-switch. Stopping flow.")
        #     fgt_set_sensorRegulation(0, 0, 0)
        # else:
        #     print(f'Able to reboot successfully, M switch {switch} actuated correctly in {t2-t1} seconds')
    else:
        pass
        print(f"M switch {switch} actuated correctly in {t2-t1} seconds")

        return 0


if __name__ == "__main__":
    n_faults = run()
```

**Comment by Ygor-Oliveira** [comment] 2022-12-07 13:09
Hello,

We've made a slightly modified version of you script. It avoids setting the valve to the position it is already in, and outputs all successful and failed commands to a file on your working directory, in a format we can analyze more easily. Running this script with our instruments, we found that it only fails with one of the 3 switches we used, which had already been identified as defective. When it fails, we can hear the switch reset to the home position as if it had been powered off and on, instead of moving to the requested position, so we believe that this is a hardware and/or power supply issue, rather than a software issue. Could you run this new script on your setup and send us the output file so we can confirm that it is a similar problem? Attached is our modified script and the log output from our run.

Best,
Ygor

[fgt_script_output.log](https://github.com/Fluigent/fgt-SDK/files/10176222/fgt_script_output.log)
[fgt_test_m_switches.txt](https://github.com/Fluigent/fgt-SDK/files/10176227/fgt_test_m_switches.txt)

**Comment by jsakkos-curio** [comment] 2022-12-07 19:51
Ygor,

Thanks for the test code. I verified that it works as expected on the 3 switches I tried. Interestingly, if you remove the call to get the valve position and replace it with a static or random variable instead of polling the device, our usual error is reproduced almost immediately. It might help avoid some of these issues to either implicitly call `fgt_get_valvePosition` when changing the switch position (i.e., bake it into the `fgt_set_valvePosition` code), or update the documentation/example scripts to make the user aware of this bug.

Jonathan

**Comment by Ygor-Oliveira** [comment] 2022-12-08 08:45
Hello again Jonathan,

I do not think this is a bug. The SDK is always polling the instruments in a background thread, and calling "get" functions simply returns the latest value it has cached in memory, without triggering any additional communication with the instruments.

The problem is that if you select a new position randomly, there is a chance that you will select the position that the switch is already in, in which case the function will return immediately since there is nothing to do. This is not counted as an error by the SDK, but it is seen as a failure in this script. To avoid this false alarm, you have to know the starting position in order to avoid selecting it again or to ignore the short duration in this case. I did that by getting the current position from the SDK, but you could also cache the positions in a dictionary in the script itself and get the same results. Attached is another version demonstrating that. If you have problems with this one, please send us the log so we can take a look at it.

Best,
Ygor

[fgt_test_m_switches.txt](https://github.com/Fluigent/fgt-SDK/files/10183552/fgt_test_m_switches.txt)

**Comment by mtrellet** [comment] 2023-04-05 08:07
@jsakkos-curio May I close this issue?

**Comment by jsakkos-curio** [comment] 2023-04-05 16:08
Yes, thank you @mtrellet .

**Closed** 2023-04-05 20:20 UTC
